import { Serie } from "./Serie.js";
export const series = [
    new Serie(1, "Dexter", "SHOWTIME", 8, "Dexter es un forense especializado en análisis de salpicaduras de sangre en el Departamento de Policía de Miami. También es un fiel novio, un divertido padrastro, un hermano confidente y ―para algunos― un freak de la sangre.", "https://www.paramountplus.com/co/shows/dexter-original-sin/", "https://th.bing.com/th/id/R.101e8a8b8b70ea2e50702b823e53eb7b?rik=8%2fGPfwhXNK1zLA&riu=http%3a%2f%2fcineargentinohoy.com.ar%2fwp-content%2fuploads%2f2020%2f10%2fBanner-Op.jpg&ehk=qRV%2f9EnIjNJaJbIb1zsUNpzsb%2fx%2bUX8c05wZpVdAFOM%3d&risl=&pid=ImgRaw&r=0"),
    new Serie(2, "Prison Break", "FOX", 5, "Lincoln es sentenciado a muerte y enviado a la Penitenciaría Estatal Fox River, para cumplir allí su condena hasta el día de su ejecución. Michael Scofield, el hermano menor de Lincoln, está convencido de la inocencia de su hermano y elabora un plan de escape.", "https://www.disneyplus.com/es-co/browse/entity-d1d023da-ebb7-474c-b858-c4890e2d5757?irclickid=zHq1qZxAFxycUObQ6ERT8R0XUksy-EW%3A%3A1hGxE0&irgwc=1&cid=DSS-Affiliate-Impact-Content-JustWatch%20GmbH-705874&tgclid=04010036-f24c-4cde-a200-033d67f98baf&gad_source=7&dclid=CObB9p340IwDFZCnWgUdAwIQ8w", "https://m.media-amazon.com/images/S/pv-target-images/ff11705f687f07e0114c01a790fad59f7d8a1a69c0f5942615f2f62f6a6cf4d3.jpg"),
    new Serie(3, "Lost", "SYFY", 6, "Un avión se estrella en una isla remota. Los 48 supervivientes luchan por sobrevivir, pero pronto descubren que este lugar no es normal. Entre la jungla hay sonidos misteriosos, una criatura invisible y un grupo de habitantes que no deberían estar allí.", "https://www.netflix.com/co/title/70136118", "https://th.bing.com/th/id/OIP.kU8WwZQOaQu56c9yqTjfWAHaEc?rs=1&pid=ImgDetMain"),
    new Serie(4, "Supernatural", "WB", 15, "Sam y Winchester Dean recorren Estados Unidos en su Chevy Impala '67, cazando todo lo que no debería existir: demonios, vampiros, fantasmas y hasta ángeles caídos.", "https://www.primevideo.com/detail?gti=amzn1.dv.gti.f90e3613-4314-4f09-a93e-dae5944d92a3&irclickid=f8660993N6d8111efb30d19a7abef729&ref=dvm_ass_acm_xx_mf_s_imp_f8660993N6d8111efb30d19a7abef729&irgwc=1", "https://www.bing.com/images/search?FORM=IARRTH&q=supernatural&id=OSK.c_ho76j4oF_zoLtfMDf2AIR-gm8KaXWfVtm-ddnfpCs"),
    new Serie(5, "Narcos", "NETFLIX", 3, "La verdadera historia de los poderosos y violentos cárteles de droga colombianos es el marco de esta serie dramática sobre el narco.", "https://www.netflix.com/co/title/80025172", "https://www.reviewsxp.com/blog/wp-content/uploads/2020/04/narcos.jpg"),
    new Serie(6, "NarcoSantos", "NETFLIX", 1, "Un empresario se une a una misión secreta del Gobierno para capturar a un capo de la droga coreano que opera en Sudamérica. Basada en hechos reales.", "https://www.netflix.com/co/title/81343748", "https://pics.filmaffinity.com/Narcosantos_Serie_de_TV-208317787-large.jpg")
];
